<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('surname')->nullable();
            $table->string('username')->unique()->nullable();
            $table->integer('phone_number')->unique()->nullable();
            $table->enum('gender', ['male', 'female', 'other', 'prefer_not_to_say'])->default("prefer_not_to_say");
            $table->date('birthdate')->nullable();
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->foreignId('current_team_id')->nullable();
            $table->longText('profile_photo_path')->nullable();
            $table->enum('rol', ['user', 'admin'])->default("user");
            $table->enum('country', [
                "TV",
                "BV",
                "GI",
                "GO",
                "JU",
                "UM-DQ",
                "UM-FQ",
                "UM-HQ",
                "UM-JQ",
                "UM-MQ",
                "UM-WQ",
                "BQ",
                "NL",
                "ZW",
                "ZM",
                "ZA",
                "YE",
                "WS",
                "WF",
                "PS",
                "VU",
                "VN",
                "VI",
                "VG",
                "VE",
                "VC",
                "VA",
                "UZ",
                "US",
                "UY",
                "UA",
                "UG",
                "TZ",
                "TW",
                "TR",
                "TN",
                "TT",
                "TO",
                "TL",
                "TM",
                "TK",
                "TJ",
                "TH",
                "TG",
                "TD",
                "TC",
                "SY",
                "SC",
                "SX",
                "SZ",
                "SE",
                "SI",
                "SK",
                "SR",
                "ST",
                "RS",
                "PM",
                "SO",
                "SM",
                "SV",
                "SL",
                "SB",
                "SH",
                "GS",
                "SG",
                "SN",
                "SS",
                "SD",
                "SA",
                "EH",
                "RW",
                "RU",
                "RO",
                "RE",
                "QA",
                "PF",
                "PY",
                "PT",
                "KP",
                "PR",
                "PL",
                "PG",
                "PW",
                "PH",
                "PE",
                "PN",
                "PA",
                "PK",
                "OM",
                "NZ",
                "SJ",
                "NR",
                "NP",
                "NO",
                "NU",
                "NI",
                "NG",
                "NF",
                "NE",
                "NC",
                "NA",
                "YT",
                "MY",
                "MW",
                "MU",
                "MQ",
                "MS",
                "MR",
                "MZ",
                "MP",
                "MN",
                "ME",
                "MM",
                "MT",
                "ML",
                "MK",
                "MH",
                "MX",
                "MV",
                "MG",
                "MD",
                "MC",
                "MA",
                "MF",
                "MO",
                "LV",
                "LU",
                "LT",
                "LS",
                "LK",
                "LI",
                "LC",
                "LY",
                "LR",
                "LB",
                "LA",
                "KW",
                "XK",
                "KR",
                "KN",
                "KI",
                "KH",
                "KG",
                "KE",
                "KZ",
                "JP",
                "JO",
                "JE",
                "JM",
                "IT",
                "IL",
                "IS",
                "IQ",
                "IR",
                "IE",
                "IO",
                "IN",
                "IM",
                "ID",
                "HU",
                "HT",
                "HR",
                "HN",
                "HM",
                "HK",
                "GY",
                "GU",
                "GF",
                "GT",
                "GL",
                "GD",
                "GR",
                "GQ",
                "GW",
                "GM",
                "GP",
                "GN",
                "GH",
                "GG",
                "GE",
                "GA",
                "FR",
                "FM",
                "FO",
                "FK",
                "FJ",
                "FI",
                "ET",
                "EE",
                "ES",
                "ER",
                "GB",
                "EG",
                "EC",
                "DZ",
                "DO",
                "DK",
                "DM",
                "DJ",
                "DE",
                "CZ",
                "CY",
                "KY",
                "CX",
                "CW",
                "CU",
                "CR",
                "CV",
                "KM",
                "CO",
                "CK",
                "CG",
                "CD",
                "CM",
                "CI",
                "CN",
                "CL",
                "CH",
                "CC",
                "CA",
                "CF",
                "BE",
                "BW",
                "BT",
                "BN",
                "BB",
                "BR",
                "BO",
                "BM",
                "BZ",
                "BY",
                "BL",
                "BS",
                "BH",
                "BA",
                "BG",
                "BD",
                "BF",
                "BJ",
                "BI",
                "AZ",
                "AT",
                "AU",
                "TF",
                "AQ",
                "AS",
                "AM",
                "AR",
                "AE",
                "AD",
                "AX",
                "AL",
                "AI",
                "AO",
                "AF",
                "AG",
                "AW"
            ])->default("ES"); // Default is set to Spain
            $table->timestamps();
        });



        Schema::create('password_reset_tokens', function (Blueprint $table) {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });

        Schema::create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->foreignId('user_id')->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->longText('payload');
            $table->integer('last_activity')->index();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('sessions');
    }
};
