<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Genera fechas aleatorias entre el 1 de enero de 2024 y la fecha y hora actual
        $startDate = strtotime('2024-01-01');
        $endDate = now()->timestamp;
        $randomDate = mt_rand($startDate, $endDate);

        // Ruta de la imagen en tu computadora
        $imagen = 'public/images/blank-profile-picture.png';

        // Leer el contenido de la imagen como datos binarios
        $datosImagen = file_get_contents($imagen);

        // Codificar los datos binarios en una cadena base64
        $imagenBase64 = base64_encode($datosImagen);

        // Crear el objeto BLOB
        $blob = "data:image/jpeg;base64," . $imagenBase64;

        return [
            'name' => fake()->name(),
            'surname' => $this->faker->lastName,
            'username' => $this->faker->unique()->userName,
            'phone_number' => $this->faker->unique()->numerify('6########'),
            'gender' => $this->faker->randomElement(['male', 'female', 'other', 'prefer_not_to_say']),
            'birthdate' => $this->faker->date(),
            'email' => fake()->unique()->safeEmail(),
            'email_verified_at' => now(),
            'password' => static::$password ??= Hash::make('password'),
            'remember_token' => Str::random(10),
            'profile_photo_path' => $blob,
            'current_team_id' => null,
            'country' => $this->faker->randomElement([
                "TV",
                "BV",
                "GI",
                "GO",
                "JU",
                "UM-DQ",
                "UM-FQ",
                "UM-HQ",
                "UM-JQ",
                "UM-MQ",
                "UM-WQ",
                "BQ",
                "NL",
                "ZW",
                "ZM",
                "ZA",
                "YE",
                "WS",
                "WF",
                "PS",
                "VU",
                "VN",
                "VI",
                "VG",
                "VE",
                "VC",
                "VA",
                "UZ",
                "US",
                "UY",
                "UA",
                "UG",
                "TZ",
                "TW",
                "TR",
                "TN",
                "TT",
                "TO",
                "TL",
                "TM",
                "TK",
                "TJ",
                "TH",
                "TG",
                "TD",
                "TC",
                "SY",
                "SC",
                "SX",
                "SZ",
                "SE",
                "SI",
                "SK",
                "SR",
                "ST",
                "RS",
                "PM",
                "SO",
                "SM",
                "SV",
                "SL",
                "SB",
                "SH",
                "GS",
                "SG",
                "SN",
                "SS",
                "SD",
                "SA",
                "EH",
                "RW",
                "RU",
                "RO",
                "RE",
                "QA",
                "PF",
                "PY",
                "PT",
                "KP",
                "PR",
                "PL",
                "PG",
                "PW",
                "PH",
                "PE",
                "PN",
                "PA",
                "PK",
                "OM",
                "NZ",
                "SJ",
                "NR",
                "NP",
                "NO",
                "NU",
                "NI",
                "NG",
                "NF",
                "NE",
                "NC",
                "NA",
                "YT",
                "MY",
                "MW",
                "MU",
                "MQ",
                "MS",
                "MR",
                "MZ",
                "MP",
                "MN",
                "ME",
                "MM",
                "MT",
                "ML",
                "MK",
                "MH",
                "MX",
                "MV",
                "MG",
                "MD",
                "MC",
                "MA",
                "MF",
                "MO",
                "LV",
                "LU",
                "LT",
                "LS",
                "LK",
                "LI",
                "LC",
                "LY",
                "LR",
                "LB",
                "LA",
                "KW",
                "XK",
                "KR",
                "KN",
                "KI",
                "KH",
                "KG",
                "KE",
                "KZ",
                "JP",
                "JO",
                "JE",
                "JM",
                "IT",
                "IL",
                "IS",
                "IQ",
                "IR",
                "IE",
                "IO",
                "IN",
                "IM",
                "ID",
                "HU",
                "HT",
                "HR",
                "HN",
                "HM",
                "HK",
                "GY",
                "GU",
                "GF",
                "GT",
                "GL",
                "GD",
                "GR",
                "GQ",
                "GW",
                "GM",
                "GP",
                "GN",
                "GH",
                "GG",
                "GE",
                "GA",
                "FR",
                "FM",
                "FO",
                "FK",
                "FJ",
                "FI",
                "ET",
                "EE",
                "ES",
                "ER",
                "GB",
                "EG",
                "EC",
                "DZ",
                "DO",
                "DK",
                "DM",
                "DJ",
                "DE",
                "CZ",
                "CY",
                "KY",
                "CX",
                "CW",
                "CU",
                "CR",
                "CV",
                "KM",
                "CO",
                "CK",
                "CG",
                "CD",
                "CM",
                "CI",
                "CN",
                "CL",
                "CH",
                "CC",
                "CA",
                "CF",
                "BE",
                "BW",
                "BT",
                "BN",
                "BB",
                "BR",
                "BO",
                "BM",
                "BZ",
                "BY",
                "BL",
                "BS",
                "BH",
                "BA",
                "BG",
                "BD",
                "BF",
                "BJ",
                "BI",
                "AZ",
                "AT",
                "AU",
                "TF",
                "AQ",
                "AS",
                "AM",
                "AR",
                "AE",
                "AD",
                "AX",
                "AL",
                "AI",
                "AO",
                "AF",
                "AG",
                "AW"
            ]),
            'created_at' => date('Y-m-d H:i:s', $randomDate), // Establece 'created_at' en la fecha aleatoria generada
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }
}
